### ISSUE TITLE
RHEL / CentOS / RockyLinux install failing with 'All matches were filtered out'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php-redis#5]
CI tests are failing:

```
TASK [geerlingguy.php-redis : Install PhpRedis extension (RedHat).] ************
fatal: [instance]: FAILED! => {"changed": false, "failures": ["php-pecl-redis5 All matches were filtered out by modular filtering for argument: php-pecl-redis5"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

Some bit of packaging voodoo might be required here. I tried switching to EPEL but that didn't seem to work.

**Comment by geerlingguy** [comment]
lol 'still a bug' ;)

**Comment by candra-wahab** [comment]
Hi @geerlingguy i have error ansible running role.yaml
fatal: [node4]: FAILED! => {"changed": false, "failures": ["No package php-xmlrpc available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [node5]: FAILED! => {"changed": false, "failures": ["No package php-xmlrpc available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
can you help me?

**Comment by efostevo** [comment]
any update please

**Comment by geerlingguy** [comment]
@candra-wahab - Please see https://github.com/geerlingguy/ansible-role-php/issues/423 as well

**Comment by geerlingguy** [comment]
This should be fixed now, however idempotence tests are failing. New issue: #6
